version: "3.0"

services:
  predix-edge-node-red:
    image: "predixadoption/predix-edge-node-red:1.0.18"
    volumes:
      - ./config:/config
      - ./data:/data
    networks:
      - predix-edge-broker_net
    ports:
      - 1880:1880
networks:
  predix-edge-broker_net:
    external: true
